# Generated by pip2nix 0.7.0.dev1
# See https://github.com/johbo/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  Jinja2 = super.buildPythonPackage {
    name = "Jinja2-2.10";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [MarkupSafe];
    src = fetchurl {
      url = "https://pypi.python.org/packages/56/e6/332789f295cf22308386cf5bbd1f4e00ed11484299c5d7383378cf48ba47/Jinja2-2.10.tar.gz";
      sha256 = "190l36hfw3wb2n3n68yacjabxyb1pnxwn7vjx96cmjj002xy2jzq";
    };
  };
  MarkupSafe = super.buildPythonPackage {
    name = "MarkupSafe-1.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz";
      sha256 = "0rdn1s8x9ni7ss8rfiacj7x1085lx8mh2zdwqslnw8xc3l4nkgm6";
    };
  };
  Pygments = super.buildPythonPackage {
    name = "Pygments-2.2.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/71/2a/2e4e77803a8bd6408a2903340ac498cb0a2181811af7c9ec92cb70b0308a/Pygments-2.2.0.tar.gz";
      sha256 = "1k78qdvir1yb1c634nkv6rbga8wv4289xarghmsbbvzhvr311bnv";
    };
  };
  alabaster = super.buildPythonPackage {
    name = "alabaster-0.7.10";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/d0/a5/e3a9ad3ee86aceeff71908ae562580643b955ea1b1d4f08ed6f7e8396bd7/alabaster-0.7.10.tar.gz";
      sha256 = "1q3z4lf39qndwcjg3gbscck8q5qjklma275w5s8n1valk6gcpk9p";
    };
  };
  astunparse = super.buildPythonPackage {
    name = "astunparse-1.5.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [wheel six];
    src = fetchurl {
      url = "https://pypi.python.org/packages/1a/b7/3ba7ce33cbc8847e20ed1a4fbec2303a71b2512dec0194824e8dcaadc8de/astunparse-1.5.0.tar.gz";
      sha256 = "1kc9lm2jvfcip3z8snj04dar5a9jh857a704m6lvcv4xclm3rpsm";
    };
  };
  babel = super.buildPythonPackage {
    name = "babel-2.5.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [pytz];
    src = fetchurl {
      url = "https://pypi.python.org/packages/5a/22/63f1dbb8514bb7e0d0c8a85cc9b14506599a075e231985f98afd70430e1f/Babel-2.5.1.tar.gz";
      sha256 = "04aqsbb2r3g4869mb2b2ls6yc81w5gaf4dp4pcj5bkfh2kvxl1v0";
    };
  };
  certifi = super.buildPythonPackage {
    name = "certifi-2017.11.5";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/23/3f/8be01c50ed24a4bd6b8da799839066ce0288f66f5e11f0367323467f0cbc/certifi-2017.11.5.tar.gz";
      sha256 = "1h0k6sy3p4csfdayghg2wjbnb1hfz27i5qbr0c7v8dhira8l5isy";
    };
  };
  chardet = super.buildPythonPackage {
    name = "chardet-3.0.4";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz";
      sha256 = "1bpalpia6r5x1kknbk11p1fzph56fmmnp405ds8icksd3knr5aw4";
    };
  };
  coverage = super.buildPythonPackage {
    name = "coverage-4.4.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/0b/e1/190ef1a264144c9b073b7353c259ca5431b5ddc8861b452e858fcbd0e9de/coverage-4.4.2.tar.gz";
      sha256 = "1k1l1xdpzni35xrffwv3nvqb7ylb912mdmz4l33kw1imgayr379h";
    };
  };
  docutils = super.buildPythonPackage {
    name = "docutils-0.14";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/84/f4/5771e41fdf52aabebbadecc9381d11dea0fa34e4759b4071244fa094804c/docutils-0.14.tar.gz";
      sha256 = "0x22fs3pdmr42kvz6c654756wja305qv6cx1zbhwlagvxgr4xrji";
    };
  };
  flake8 = super.buildPythonPackage {
    name = "flake8-3.5.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [pyflakes pycodestyle mccabe setuptools];
    src = fetchurl {
      url = "https://pypi.python.org/packages/1e/ab/7730f6d6cdf73a3b7f98a2fe3b2cdf68e9e760a4a133e083607497d4c3a6/flake8-3.5.0.tar.gz";
      sha256 = "184b33grvvjmiwlv9kyd7yng9qv5ld24154j70z332xxg9gjclvj";
    };
  };
  flake8-blind-except = super.buildPythonPackage {
    name = "flake8-blind-except-0.1.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [setuptools];
    src = fetchurl {
      url = "https://pypi.python.org/packages/ff/f2/ab635e6e420e78c94eab50cd3f53abd3ec27e411793e50b14f29edbb9f0b/flake8-blind-except-0.1.1.tar.gz";
      sha256 = "16g58mkr3fcn2vlfhp3rlahj93qswc7jd5qrqp748mc26dk3b8xc";
    };
  };
  flake8-coding = super.buildPythonPackage {
    name = "flake8-coding-1.3.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [flake8];
    src = fetchurl {
      url = "https://pypi.python.org/packages/ae/26/3c6304d646f8ee27d6c40bfcd9874fea870098c3ef3cf60e284ea9db29ef/flake8-coding-1.3.0.tar.gz";
      sha256 = "1gjhzv85gaviwszp04l3win3h69bhfd4kwvi7mm7cxwkhxpyj0ds";
    };
  };
  flake8-debugger = super.buildPythonPackage {
    name = "flake8-debugger-3.0.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [flake8 pycodestyle];
    src = fetchurl {
      url = "https://pypi.python.org/packages/2c/a7/45823a26ef0c5fa7a0c099b772a5b6aa2d8e686284490ef738fc8691ffc0/flake8-debugger-3.0.0.tar.gz";
      sha256 = "1m6jqgdbpq7plf24kknnxlkw3rig7bjf17xqzgrv57c11ncarj75";
    };
  };
  flake8-isort = super.buildPythonPackage {
    name = "flake8-isort-2.2.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [flake8 flake8-polyfill isort testfixtures];
    src = fetchurl {
      url = "https://pypi.python.org/packages/07/2b/196a65996ae39cf8d9c5edc7116b41ac06a605c7e8a2ca039cca8c050e5d/flake8-isort-2.2.2.tar.gz";
      sha256 = "0411nhkz0gcmd5wfd6wkhhj0kadnbxipa3w3fssnz0lhyzcy37jb";
    };
  };
  flake8-polyfill = super.buildPythonPackage {
    name = "flake8-polyfill-1.0.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [flake8];
    src = fetchurl {
      url = "https://pypi.python.org/packages/71/6e/dd7e0f0ddf146213d0cc0b963b3d4c6434823ebe3992c29b523182bbf785/flake8-polyfill-1.0.1.tar.gz";
      sha256 = "02gn2wxvh9vnf7m7dld7ca4l60mg5c370hv3swwppkngwaqmcw67";
    };
  };
  flake8-quotes = super.buildPythonPackage {
    name = "flake8-quotes-0.12.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [flake8];
    src = fetchurl {
      url = "https://pypi.python.org/packages/a0/4f/60ff2549d4b4abb3665f7019184652f5bd9a421ad7312cc1aef644317441/flake8-quotes-0.12.0.zip";
      sha256 = "195cxk43d868qw1nmn1nvs7h42s07rk2if701cx1py3p8xazws8l";
    };
  };
  idna = super.buildPythonPackage {
    name = "idna-2.6";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/f4/bd/0467d62790828c23c47fc1dfa1b1f052b24efdf5290f071c7a91d0d82fd3/idna-2.6.tar.gz";
      sha256 = "13qaab6d0s15gknz8v3zbcfmbj6v86hn9pjxgkdf62ch13imssic";
    };
  };
  imagesize = super.buildPythonPackage {
    name = "imagesize-0.7.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/53/72/6c6f1e787d9cab2cc733cf042f125abec07209a58308831c9f292504e826/imagesize-0.7.1.tar.gz";
      sha256 = "0qk07k0z4241lkzzjji7z4da04pcvg7bfc4xz1934zlqhwmwdcha";
    };
  };
  isort = super.buildPythonPackage {
    name = "isort-4.2.15";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/4d/d5/7c8657126a43bcd3b0173e880407f48be4ac91b4957b51303eab744824cf/isort-4.2.15.tar.gz";
      sha256 = "10rr1grpsxnjrxgnfdjwabn8nlwbgb667rhnf0zfbqm4sdr63x3r";
    };
  };
  mccabe = super.buildPythonPackage {
    name = "mccabe-0.6.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/06/18/fa675aa501e11d6d6ca0ae73a101b2f3571a565e0f7d38e062eec18a91ee/mccabe-0.6.1.tar.gz";
      sha256 = "07w3p1qm44hgxf3vvwz84kswpsx6s7kvaibzrsx5dzm0hli1i3fx";
    };
  };
  olefile = super.buildPythonPackage {
    name = "olefile-0.44";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/35/17/c15d41d5a8f8b98cc3df25eb00c5cee76193114c78e5674df6ef4ac92647/olefile-0.44.zip";
      sha256 = "1bbk1xplmrhymqpk6rkb15sg7v9qfih7zh23p6g2fxxas06cmwk1";
    };
  };
  pdfrw = super.buildPythonPackage {
    name = "pdfrw-0.4";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/61/96/cbde98b96115d10694010e584d00d39f7b97905e1c8303e6ffbb84080e6a/pdfrw-0.4.tar.gz";
      sha256 = "1x1yp63lg3jxpg9igw8lh5rc51q353ifsa1bailb4qb51r54kh0d";
    };
  };
  pep8-naming = super.buildPythonPackage {
    name = "pep8-naming-0.4.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/c8/c9/d16bea3e5f888f430b73f44eb9be8ba3cd7a22f08ed05363c8614b131e21/pep8-naming-0.4.1.tar.gz";
      sha256 = "0nhf8p37y008shd4f21bkj5pizv8q0l8cpagyyb8gr059d6gvvaf";
    };
  };
  pillow = super.buildPythonPackage {
    name = "pillow-4.3.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [olefile];
    src = fetchurl {
      url = "https://pypi.python.org/packages/e0/82/ec499c78bfe4ecaa91c2f3000040451d187ed0a816d58b8543e29c48827f/Pillow-4.3.0.tar.gz";
      sha256 = "09xmn7rl6840sli2iz1k3fgxfgmri2nqz6vkinmb9mgg8ifp2z59";
    };
  };
  pip = super.buildPythonPackage {
    name = "pip-9.0.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/11/b6/abcb525026a4be042b486df43905d6893fb04f05aac21c32c638e939e447/pip-9.0.1.tar.gz";
      sha256 = "03clr9c1dih5n9c00c592zzvf6r1ffimywkaq9agcqdllzhl7wh9";
    };
  };
  py = super.buildPythonPackage {
    name = "py-1.5.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/90/e3/e075127d39d35f09a500ebb4a90afd10f9ef0a1d28a6d09abeec0e444fdd/py-1.5.2.tar.gz";
      sha256 = "0vd7i2lspzfwj0k68cnm1pk3rclnrnkavgqncdsifm1350z9866a";
    };
  };
  pycodestyle = super.buildPythonPackage {
    name = "pycodestyle-2.3.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/e1/88/0e2cbf412bd849ea6f1af1f97882add46a374f4ba1d2aea39353609150ad/pycodestyle-2.3.1.tar.gz";
      sha256 = "0rk78b66p57ala26mdldl9lafr48blv5s659sah9q50qnfjmc8k8";
    };
  };
  pyflakes = super.buildPythonPackage {
    name = "pyflakes-1.6.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/26/85/f6a315cd3c1aa597fb3a04cc7d7dbea5b3cc66ea6bd13dfa0478bf4876e6/pyflakes-1.6.0.tar.gz";
      sha256 = "01c87qiadz71sbqrclrsr85vx601p20g4hs7nlcvyg945ww6lqcd";
    };
  };
  pytest = super.buildPythonPackage {
    name = "pytest-3.2.5";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [py setuptools];
    src = fetchurl {
      url = "https://pypi.python.org/packages/1f/f8/8cd74c16952163ce0db0bd95fdd8810cbf093c08be00e6e665ebf0dc3138/pytest-3.2.5.tar.gz";
      sha256 = "10cbsyyyzamhvi1gqqyhccsx906xlcwcgddvldalqi1v27vx8nvd";
    };
  };
  pytest-cov = super.buildPythonPackage {
    name = "pytest-cov-2.5.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [pytest coverage];
    src = fetchurl {
      url = "https://pypi.python.org/packages/24/b4/7290d65b2f3633db51393bdf8ae66309b37620bc3ec116c5e357e3e37238/pytest-cov-2.5.1.tar.gz";
      sha256 = "0bbfpwdh9k3636bxc88vz9fa7vf4akchgn513ql1vd0xy4n7bah3";
    };
  };
  pytest-runner = super.buildPythonPackage {
    name = "pytest-runner-3.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/65/b4/ae89338cd2d81e2cc54bd6db2e962bfe948f612303610d68ab24539ac2d1/pytest-runner-3.0.tar.gz";
      sha256 = "00v7pi09q60yx0l1kzyklnmr5bp597mir85a9gsi7bdfyly3lz0g";
    };
  };
  pytz = super.buildPythonPackage {
    name = "pytz-2017.3";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/60/88/d3152c234da4b2a1f7a989f89609ea488225eaea015bc16fbde2b3fdfefa/pytz-2017.3.zip";
      sha256 = "1dw5l527vcafvdqq4wadwl7ikhb2sssz0v0cssibh8890kyczr7s";
    };
  };
  reportlab = super.buildPythonPackage {
    name = "reportlab-3.4.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [pillow pip setuptools];
    src = fetchurl {
      url = "https://pypi.python.org/packages/87/f9/53b34c58d3735a6df7d5c542bf4de60d699cfa6035e113ca08b3ecdcca3f/reportlab-3.4.0.tar.gz";
      sha256 = "0hy304pzsz9lblmk7mrbk2682bi911lxgvzx2kcfpmfzb5gg7sjv";
    };
  };
  requests = super.buildPythonPackage {
    name = "requests-2.18.4";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [chardet idna urllib3 certifi];
    src = fetchurl {
      url = "https://pypi.python.org/packages/b0/e1/eab4fc3752e3d240468a8c0b284607899d2fbfb236a56b7377a329aa8d09/requests-2.18.4.tar.gz";
      sha256 = "0zi3v9nsmv9j27d0c0m1dvqyvaxz53g8m0aa1h3qanxs4irkwi4w";
    };
  };
  rst2pdf = super.buildPythonPackage {
    name = "rst2pdf-0.93.dev0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [setuptools docutils reportlab Pygments pdfrw];
    src = fetchurl {
      url = "https://pypi.python.org/packages/7a/28/3c7e1d6d68165dc74a5b65ed3d2150caaeabb49952d38f639e97d37d6984/rst2pdf-0.93.tar.gz";
      sha256 = "1g7w7qv8qrrdyjd5xjabzs7cg9kc21qqv3vf52l3146irs1l5x1s";
    };
  };
  setuptools = super.buildPythonPackage {
    name = "setuptools-36.7.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/0f/22/7fdcc777ba60e2a8b1ea17f679c2652ffe80bd5a2f35d61c629cb9545d5e/setuptools-36.7.2.zip";
      sha256 = "03928x49iacgnl58pxxfgxiq666j46y2pf65nhrmqa4ws26zv1md";
    };
  };
  setuptools-scm = super.buildPythonPackage {
    name = "setuptools-scm-1.15.6";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/03/6d/aafdd01edd227ee879b691455bf19895091872af7e48192bea1758c82032/setuptools_scm-1.15.6.tar.gz";
      sha256 = "0pzvfmx8s20yrgkgwfbxaspz2x1g38qv61jpm0ns91lrb22ldas9";
    };
  };
  six = super.buildPythonPackage {
    name = "six-1.11.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz";
      sha256 = "1scqzwc51c875z23phj48gircqjgnn3af8zy2izjwmnlxrxsgs3h";
    };
  };
  snapshottest = super.buildPythonPackage {
    name = "snapshottest-0.5.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [six termcolor];
    src = fetchurl {
      url = "https://pypi.python.org/packages/38/9d/6114ac51327ee8be784ebde5fb21606e161097a41eac3e0619bfc7fad0fd/snapshottest-0.5.0.tar.gz";
      sha256 = "035ljn22x11qgkllvr6h72zik5nkh9xqnz8fbai73lbz77mjhp11";
    };
  };
  snowballstemmer = super.buildPythonPackage {
    name = "snowballstemmer-1.2.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/20/6b/d2a7cb176d4d664d94a6debf52cd8dbae1f7203c8e42426daa077051d59c/snowballstemmer-1.2.1.tar.gz";
      sha256 = "0a0idq4y5frv7qsg2x62jd7rd272749xk4x99misf5rcifk2d7wi";
    };
  };
  sphinx = super.buildPythonPackage {
    name = "sphinx-1.6.5";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [six Jinja2 Pygments docutils snowballstemmer babel alabaster imagesize requests setuptools sphinxcontrib-websupport];
    src = fetchurl {
      url = "https://pypi.python.org/packages/8b/7e/b188d9a3b9c938e736e02a74c1363c2888e095d770df2c72b4c312f9fdcb/Sphinx-1.6.5.tar.gz";
      sha256 = "1670rzrgqb51cy4kfwhpkv2b6vlg1v09qf7lawkps3bspfymvpn6";
    };
  };
  sphinx-rtd-theme = super.buildPythonPackage {
    name = "sphinx-rtd-theme-0.2.4";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/8b/e5/b1933472424b30affb0a8cea8f0ef052a31ada96e5d1823911d7f4bfdf8e/sphinx_rtd_theme-0.2.4.tar.gz";
      sha256 = "05rlhjzdyapr2w74jjs7mrm8hi69qskcr5vya9f9drpsys7lpxrd";
    };
  };
  sphinx-testing = super.buildPythonPackage {
    name = "sphinx-testing-0.7.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [sphinx six];
    src = fetchurl {
      url = "https://pypi.python.org/packages/fa/b4/272ae6e8b174b00c84b55b4d330dffde16f66e8c82284a6206c06356bd5a/sphinx-testing-0.7.2.tar.gz";
      sha256 = "150yh8p39l89xy4fbds66n2snpi2lx99zwgd6dxi63k20wqgjc4x";
    };
  };
  sphinxcontrib-httpdomain = super.buildPythonPackage {
    name = "sphinxcontrib-httpdomain-1.5.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [sphinx six];
    src = fetchurl {
      url = "https://pypi.python.org/packages/a5/52/0ded71896b9d25621b44d681cdd352c37a9ed81219a6b62014bd15dd2b9e/sphinxcontrib-httpdomain-1.5.0.tar.gz";
      sha256 = "0srg8lwf4m1hyhz942fcdfxh689xphndngiidb575qmfbi89gc7a";
    };
  };
  sphinxcontrib-websupport = super.buildPythonPackage {
    name = "sphinxcontrib-websupport-1.0.1";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/c5/6b/f0630436b931ad4f8331a9399ca18a7d447f0fcc0c7178fb56b1aee68d01/sphinxcontrib-websupport-1.0.1.tar.gz";
      sha256 = "1f9f0wjpi9nhikbyaz6d19s7qvzdf1nq2g5dsh640fma4q9rd1bs";
    };
  };
  termcolor = super.buildPythonPackage {
    name = "termcolor-1.1.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz";
      sha256 = "0fv1vq14rpqwgazxg4981904lfyp84mnammw7y046491cv76jv8x";
    };
  };
  testfixtures = super.buildPythonPackage {
    name = "testfixtures-5.3.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/8e/41/f3737ea2bcb357846d931750bc4ac8ad4eaa4cb81b1b5aacb480205db888/testfixtures-5.3.0.tar.gz";
      sha256 = "1xfar653qmikwb94xj3f0xfp8dh2llxjsxipx1272d8qwl0aknnx";
    };
  };
  typing = super.buildPythonPackage {
    name = "typing-3.6.2";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/ca/38/16ba8d542e609997fdcd0214628421c971f8c395084085354b11ff4ac9c3/typing-3.6.2.tar.gz";
      sha256 = "0j8qfyni33c7415crxkia4r7w28za43sq1839y23xpc4na2bs56m";
    };
  };
  urllib3 = super.buildPythonPackage {
    name = "urllib3-1.22";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/ee/11/7c59620aceedcc1ef65e156cc5ce5a24ef87be4107c2b74458464e437a5d/urllib3-1.22.tar.gz";
      sha256 = "0kyvc9zdlxr5r96bng5rhm9a6sfqidrbvvkz64s76qs5267dli6c";
    };
  };
  wheel = super.buildPythonPackage {
    name = "wheel-0.30.0";
    buildInputs = with self; [];
    doCheck = false;
    propagatedBuildInputs = with self; [];
    src = fetchurl {
      url = "https://pypi.python.org/packages/fa/b4/f9886517624a4dcb81a1d766f68034344b7565db69f13d52697222daeb72/wheel-0.30.0.tar.gz";
      sha256 = "1j2knvhzgv71yli5nw6fxn87rrdxsx2xw8ldn28gs8z8jh5gw5cm";
    };
  };

### Test requirements

  
}
